###############################################################
#   Input file for App configuration
#
#   22.06.2019  Created by: zhenya
###############################################################
host:
    addr:               '192.168.2.44'
    name:               'raspberrypi'
    user:               'pi'
    test:               True

# Modes
debug:                  True
demo:                   True

# Models
button:
    gpio:               17

led:
    gpio:               27

motors:
    left:
        forward_gpio:   19
        backward_gpio:  16
    right:
        forward_gpio:   22
        backward_gpio:  23
    speed:              1.0

pigpio:
    gpio:               27
