###############################################################
#   Input file for App configuration
#
#   22.06.2019  Created by: zhenya
#   10.07.2019  New data structure of LEDs & Buttons
###############################################################
host:
    addr:               '192.168.2.44'
    name:               'raspberrypi'
    user:               'pi'
    test:               False

# Modes
debug:                  True
demo:                   True

# Models
buttons:
    -
        name:           'demo_button'
        color:          'red'
        gpio:           17
    -
        name:           'dummy_button'
        color:          'yellow'
        gpio:           20
leds:
    -
        color:          'red'
        gpio:            27
    -
        color:          'yellow'
        gpio:            26
motors:
    -
        side:           left
        forward_gpio:   19
        backward_gpio:  16
        speed:          0.8
    -
        side:           right
        forward_gpio:   22
        backward_gpio:  23
        speed:          0.8

pigpio:
    gpio:               27
